config/routes.rb
Rails.application.routes.draw do
  root to: "creatures#index"
  get "/creatures", to: "creatures#index", as: "creatures"
  get "/creatures/new", to: "creatures#new", as: "new_creature"
  post "/creatures", to: "creatures#create"
  get "/creatures/:id", to: "creatures#show", as: "creature"
  get "/creatures/:id/edit", to: "creatures#edit", as: "edit_creature"
  patch "/creatures/:id", to: "creatures#update"
  delete "creatures/:id", to: "creatures#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creature.rb
class Creature < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController

  def index
    @creatures = Creature.all
  end

  def new
    @creature = Creature.new
    render :new
  end

  def create
   creature = Creature.new(creature_params)
   if creature.save
     redirect_to creature_path(creature)
   end
  end

  def show
    @creature = Creature.find_by_id(params[:id])
  end

  def edit
    @creature = Creature.find_by_id(params[:id])
  end

  def update
    creature = Creature.find_by_id(params[:id])
    creature.update_attributes(creature_params)
    redirect_to creature_path(creature)
  end

  def destroy
  end

  private

  def creature_params
    params.require(:creature).permit(:name, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/views/creatures/edit.html.erb
<h1>Edit the <%= @creature.name %> creature</h1>
<br>
<%= form_for @creature do |f|%>
  <div class="form-group">
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Creature", class: "btn btn-block btn-success"%>
  </div>
<% end %>

<br>
<%= link_to "<- Back to this creature", creature_path(@creature) %>

app/views/creatures/index.html.erb
<h1>All of our beautiful creatures </h1>
<% @creatures.each do |creature| %>
  <p>
    <strong>Name:</strong> <%= link_to creature.name, creature_path(creature) %> <br>
    <strong>Description:</strong> <%= creature.description %>
  </p>
<% end %>
<br>
<%= link_to "Add a new creature", new_creature_path %>

app/views/creatures/new.html.erb
<h1>Create a new creature</h1>
<%= form_for :creature, url: "/creatures", method: "post" do |f|%>
  <div class="form-group">
    <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
  </div>
  <div class="form-group">
    <%= f.text_field :description, class: "form-control", placeholder: "Description" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save Creature", class: "btn btn-block btn-success"%>
  </div>
<% end %>
<br>
<%= link_to '<- Back to all creatures', creatures_path %>

app/views/creatures/show.html.erb
<h1>Look at this beauty!</h1>

<h3><%= @creature.name %></h3>
<p><%= @creature.description %></p>
<br>
<%= link_to "Edit this creature", edit_creature_path(@creature), class: "btn btn-xs btn-info" %>
<br>
<%= link_to "<- Back to all creatures", creatures_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BogApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>